// Manga action types
export const MANGA_TYPES = {
    // Manga list
    FETCH_MANGA_LIST_REQUEST: "FETCH_MANGA_LIST_REQUEST",
    FETCH_MANGA_LIST_SUCCESS: "FETCH_MANGA_LIST_SUCCESS",
    FETCH_MANGA_LIST_FAILURE: "FETCH_MANGA_LIST_FAILURE",

    // Recently added manga
    FETCH_RECENT_REQUEST: "FETCH_RECENT_REQUEST",
    FETCH_RECENT_SUCCESS: "FETCH_RECENT_SUCCESS",
    FETCH_RECENT_FAILURE: "FETCH_RECENT_FAILURE",

    // Manga details
    FETCH_MANGA_DETAILS_REQUEST: "FETCH_MANGA_DETAILS_REQUEST",
    FETCH_MANGA_DETAILS_SUCCESS: "FETCH_MANGA_DETAILS_SUCCESS",
    FETCH_MANGA_DETAILS_FAILURE: "FETCH_MANGA_DETAILS_FAILURE",

    // Legacy types
    FETCH_POPULAR_REQUEST: "FETCH_POPULAR_REQUEST",
    FETCH_POPULAR_SUCCESS: "FETCH_POPULAR_SUCCESS",
    FETCH_POPULAR_FAILURE: "FETCH_POPULAR_FAILURE",
    FETCH_DETAILS_REQUEST: "FETCH_DETAILS_REQUEST",
    FETCH_DETAILS_SUCCESS: "FETCH_DETAILS_SUCCESS",
    FETCH_DETAILS_FAILURE: "FETCH_DETAILS_FAILURE",

    // Chapters
    FETCH_CHAPTERS_REQUEST: "FETCH_CHAPTERS_REQUEST",
    FETCH_CHAPTERS_SUCCESS: "FETCH_CHAPTERS_SUCCESS",
    FETCH_CHAPTERS_FAILURE: "FETCH_CHAPTERS_FAILURE",

    // Chapter details
    FETCH_CHAPTER_REQUEST: "FETCH_CHAPTER_REQUEST",
    FETCH_CHAPTER_SUCCESS: "FETCH_CHAPTER_SUCCESS",
    FETCH_CHAPTER_FAILURE: "FETCH_CHAPTER_FAILURE",

    // Search
    SEARCH_REQUEST: "SEARCH_REQUEST",
    SEARCH_SUCCESS: "SEARCH_SUCCESS",
    SEARCH_FAILURE: "SEARCH_FAILURE",

    // Bookmarks
    ADD_BOOKMARK: "ADD_BOOKMARK",
    REMOVE_BOOKMARK: "REMOVE_BOOKMARK",

    // Downloads
    ADD_DOWNLOAD: "ADD_DOWNLOAD",
    REMOVE_DOWNLOAD: "REMOVE_DOWNLOAD",
};
